import React, { useState } from 'react';
import {
  Settings as SettingsIcon,
  Bell,
  Download,
  Shield,
  Volume2,
  Trash2,
  CheckCircle2,
  Wifi,
  WifiOff,
  RefreshCw,
  Database,
  ShieldCheck,
  AlertTriangle,
} from 'lucide-react';
import { useApp } from '../context/AppContext';
import { CAREERS } from '../data/careersData';

export const Settings: React.FC = () => {
  const {
    user,
    setUser,
    selectedCareer,
    setSelectedCareerId,
    showToast,
    isOnline,
    syncStatus,
    pendingSyncCount,
    lastSyncedAt,
    triggerManualSync,
    isSimulatedOffline,
    toggleSimulateOffline,
    triggerSyncIssueTest,
  } = useApp();
  const [weeklyReminders, setWeeklyReminders] = useState(true);
  const [voiceVolume, setVoiceVolume] = useState(85);
  const [preferredVoice, setPreferredVoice] = useState('Zephyr');

  const handleExportData = () => {
    const exportObject = {
      profile: user,
      targetCareer: selectedCareer,
      exportedAt: new Date().toISOString(),
    };
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(exportObject, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `${user.name.replace(/\s+/g, '_')}_SkillGap_Report.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
    showToast('Exported complete Skill Gap Data Report!');
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8 animate-fadeIn">
      {/* Header */}
      <div>
        <h1 className="text-2xl sm:text-3xl font-extrabold text-[#171A2B] tracking-tight">
          Settings & Preferences
        </h1>
        <p className="text-sm text-gray-500 mt-0.5">
          Manage your account configurations, target career calibration, and voice assistant options.
        </p>
      </div>

      <div className="space-y-6">
        {/* Career Target Setting */}
        <div className="bg-white rounded-3xl border border-gray-200/80 p-6 sm:p-8 space-y-4 shadow-xs">
          <h3 className="text-base font-bold text-[#171A2B]">Active Target Career</h3>
          <p className="text-xs text-gray-500">
            Switching your target role immediately updates benchmark requirements, skill gaps, and roadmaps.
          </p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-2">
            {CAREERS.map((c) => (
              <div
                key={c.id}
                onClick={() => setSelectedCareerId(c.id)}
                className={`p-4 rounded-2xl border cursor-pointer text-left transition flex items-center justify-between ${
                  selectedCareer.id === c.id
                    ? 'border-[#6C63FF] bg-[#6C63FF]/5 ring-2 ring-[#6C63FF]/20 text-[#6C63FF]'
                    : 'border-gray-200 hover:border-gray-300 text-gray-700'
                }`}
              >
                <div>
                  <p className="font-bold text-sm text-[#171A2B]">{c.title}</p>
                  <p className="text-xs text-gray-400">{c.category}</p>
                </div>
                {selectedCareer.id === c.id && <CheckCircle2 className="w-5 h-5 text-[#6C63FF]" />}
              </div>
            ))}
          </div>
        </div>

        {/* Voice Assistant Preferences */}
        <div className="bg-white rounded-3xl border border-gray-200/80 p-6 sm:p-8 space-y-4 shadow-xs">
          <div className="flex items-center gap-2 text-[#6C63FF]">
            <Volume2 className="w-5 h-5" />
            <h3 className="text-base font-bold text-[#171A2B]">AI Voice Coach Options</h3>
          </div>
          <p className="text-xs text-gray-500">
            Customize the spoken responses generated by Gemini TTS and voice playback.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
            <div className="space-y-1">
              <label className="text-xs font-bold text-gray-600">Voice Persona</label>
              <select
                value={preferredVoice}
                onChange={(e) => setPreferredVoice(e.target.value)}
                className="w-full p-2.5 rounded-xl border border-gray-200 text-sm focus:outline-none focus:ring-2 focus:ring-[#6C63FF]"
              >
                <option value="Zephyr">Zephyr (Empathetic, clear career advisor)</option>
                <option value="Kore">Kore (Warm, encouraging mentor)</option>
                <option value="Puck">Puck (Direct, energetic tech coach)</option>
                <option value="Charon">Charon (Measured, deep executive tone)</option>
              </select>
            </div>

            <div className="space-y-1">
              <label className="text-xs font-bold text-gray-600">Voice Output Volume: {voiceVolume}%</label>
              <input
                type="range"
                min="0"
                max="100"
                value={voiceVolume}
                onChange={(e) => setVoiceVolume(Number(e.target.value))}
                className="w-full accent-[#6C63FF] h-2 bg-gray-200 rounded-lg mt-3"
              />
            </div>
          </div>
        </div>

        {/* Local Progress Cache & Network Sync Management */}
        <div className="bg-white rounded-3xl border border-gray-200/80 p-6 sm:p-8 space-y-5 shadow-xs">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 text-[#6C63FF]">
              <Database className="w-5 h-5" />
              <h3 className="text-base font-bold text-[#171A2B]">Offline Caching & Data Sync</h3>
            </div>
            <span
              className={`px-3 py-1 rounded-full text-xs font-bold flex items-center gap-1.5 ${
                !isOnline
                  ? 'bg-amber-100 text-amber-900'
                  : syncStatus === 'sync_issue'
                  ? 'bg-rose-100 text-rose-900'
                  : syncStatus === 'syncing'
                  ? 'bg-indigo-100 text-[#6C63FF]'
                  : 'bg-emerald-100 text-emerald-900'
              }`}
            >
              {!isOnline ? (
                <WifiOff className="w-3.5 h-3.5" />
              ) : syncStatus === 'sync_issue' ? (
                <AlertTriangle className="w-3.5 h-3.5" />
              ) : syncStatus === 'syncing' ? (
                <RefreshCw className="w-3.5 h-3.5 animate-spin" />
              ) : (
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-700" />
              )}
              <span className="capitalize">{syncStatus.replace('_', ' ')}</span>
            </span>
          </div>

          <p className="text-xs text-gray-500 leading-relaxed">
            SkillLens AI continuously mirrors your completed roadmap tasks, customized skill proficiency scores, and conversation logs to encrypted browser local storage (<code className="text-[#6C63FF] font-mono">skilllens_cached_progress_v1</code>). Even with lost internet connectivity, all work is retained and queue-synchronized upon reconnection.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 p-4 rounded-2xl bg-[#F7F8FC] border border-gray-100 text-xs">
            <div>
              <span className="text-gray-400 block font-medium">Local Cache Protection</span>
              <p className="font-bold text-emerald-600 flex items-center gap-1 mt-0.5">
                <ShieldCheck className="w-4 h-4" /> Enabled & Active
              </p>
            </div>
            <div>
              <span className="text-gray-400 block font-medium">Queued Local Updates</span>
              <p className="font-bold text-[#171A2B] mt-0.5">
                {pendingSyncCount} pending actions
              </p>
            </div>
            <div>
              <span className="text-gray-400 block font-medium">Last Cloud Backup</span>
              <p className="font-bold text-[#171A2B] mt-0.5">
                {lastSyncedAt ? lastSyncedAt.toLocaleTimeString() : 'Just now'}
              </p>
            </div>
          </div>

          <div className="flex flex-wrap items-center gap-3 pt-1">
            <button
              onClick={triggerManualSync}
              disabled={!isOnline}
              className="px-4 py-2 bg-[#6C63FF] hover:bg-[#5b52e0] disabled:opacity-40 text-white rounded-xl text-xs font-bold transition flex items-center gap-1.5"
            >
              <RefreshCw className="w-3.5 h-3.5" />
              <span>Force Cloud Sync</span>
            </button>

            <button
              onClick={toggleSimulateOffline}
              className={`px-4 py-2 rounded-xl text-xs font-bold border transition ${
                isSimulatedOffline
                  ? 'bg-amber-100 border-amber-300 text-amber-900 hover:bg-amber-200'
                  : 'bg-white border-gray-200 text-gray-700 hover:bg-gray-50'
              }`}
            >
              {isSimulatedOffline ? 'Resume Online Mode' : 'Simulate Offline Mode'}
            </button>

            <button
              onClick={triggerSyncIssueTest}
              className="px-3 py-2 text-xs font-semibold text-gray-500 hover:text-rose-600 transition"
            >
              Simulate Sync Warning
            </button>
          </div>
        </div>

        {/* Export & Data Privacy */}
        <div className="bg-white rounded-3xl border border-gray-200/80 p-6 sm:p-8 space-y-4 shadow-xs">
          <div className="flex items-center gap-2 text-emerald-600">
            <Download className="w-5 h-5" />
            <h3 className="text-base font-bold text-[#171A2B]">Export Career Intelligence Report</h3>
          </div>
          <p className="text-xs text-gray-500">
            Download your complete career readiness report, verified skill scores, and personalized roadmap.
          </p>
          <button
            onClick={handleExportData}
            className="px-5 py-2.5 rounded-xl bg-[#0B1020] text-white text-xs font-bold hover:bg-black transition flex items-center gap-2"
          >
            <Download className="w-4 h-4" />
            <span>Export Report (JSON)</span>
          </button>
        </div>
      </div>
    </div>
  );
};
